title = "Jay Cromwell"
baseURL = "https://jay-crom.netlify.com/"
languageCode = "en-us"
theme = "gohugo-theme-ananke"
description = "A little of everything... a lot of nothing."
#disqusShortName = "Jay C"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 10 
googleAnalytics = ""
#enableRobotsTXT = true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[menu]
 [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 1
    identifier = "home"
    url = "/"


[params]
  description = "A little of everything... a lot of nothing."
  favicon = ""
  twitter = "https://twitter.com/jaycromwell12"
  github = "https://github.com/cromwell421"
  linkedin = ""
  mastodon = ""
  background_color_class = "bg-black"
  featured_image = "/images/budapest_river_parliament.jpg"
  recent_posts_number = 4
#  commentEnable = true

  # Custom CSS. Put here your custom CSS files. They are loaded after the theme CSS;
  # they have to be referred from static root. Example
  # [[params.customCSS]]
  #   href = "css/mystyle.css"
#  custom_css = ["custom.css"]


  