---
title: Quick Thoughts - What Can Airlines Learn from 2 Chainz
author: ''
date: '2020-12-05'
slug: quick-thoughts-what-can-airlines-learn-from-2-chainz
categories: []
tags:
  - Quick Thoughts
  - Airlines
  - Marketing
description: ''
featured_image: ''
---

I’ve always joked if I were to open up a restaurant or bar, I wouldn’t focus so much on the menu but on the walls. More specifically, the exterior walls. I’d put up a huge, inviting mural on one of the walls and that would be all the marketing I’d need. I would rely on people seeking out the mural to post pictures in front of the iconic artwork, ultimately promoting my restaurant whether they ate there or not. 

This idea had me thinking about how other companies and industries could leverage similar strategies. For instance, many airlines have well known brands, but they could capitalize on organic marketing tactics to expand upon that image. A good example of this is the paint and design of the airplanes, also known as the aircraft’s livery.

Implementing a new livery for a select plane or two could bring the airline a new wave of viral promotion with little marketing investment from the firm. The more unique the design, the more attention it would bring. It would also be a great opportunity to promote social responsibility. An airline could paint an aircraft bright pink to promote breast cancer awareness. They could have a full-on green aircraft to emphasize its dedication to being environmentally conscious. 

Not only would it be a fun and worthwhile campaign, it would create a stir among passengers and the public. The airline brand would spread from social media to news outlets. Imagine walking up to your gate for a normal flight, only to see through the gate's windows that you'll be flying on the one and only “pink plane.” The excitement and exclusivity of being on the limited edition, uniquely identifiable planes would lead to organic marketing for the airline. After all, if 2 Chainz can turn a [colorful trap house](https://theundefeated.com/features/rapper-2-chainz-transforms-his-pink-trap-house-into-an-hiv-testing-center/) in Atlanta into a viral sensation, who knows what could happen with airplanes that are visible to millions of people.

The potential for the airline to gain free promotion from its livery may seem like a no brainer, but that's not to say it would be an easy and cheap operation. Painting a single aircraft can [cost anywhere from $100,000 - $200,000](https://www.wsj.com/articles/SB10001424127887323968304578247681812331570). Considering the financial struggle airlines have gone through this year, costly re-painting of aircrafts should be a like a low priority. However, airlines can plan accordingly and take advantage of an aircraft's regularly scheduled touch up. With aircrafts needing paint work [every 5 to 10 years](https://aviation.stackexchange.com/questions/13738/how-much-does-it-cost-to-give-an-airliner-a-fresh-coat-of-paint), maybe the next one up could be a candidate for a compete makeover. 

While this isn't exactly a new idea for airlines, it is not a very common occurrence, especially for US based airlines. In 2015, All Nippon Airlines, a major airline in Japan, rolled out Star Wars themed planes to much excitement from Jedi fans far and wide. Other national airlines, like [Brussels Airlines](https://www.brusselsairlines.com/com/misc/belgian-icons.aspx?utm_source=awin&utm_medium=affiliate&utm_campaign=sn_us_en_alwayson&utm_content=sn&utm_term=awin_78888&awc=5637_1607187078_279aac16f7a47eb210c247f1c524163b) and [Air New Zealand](https://cargofacts.com/allposts/news/air-new-zealand-all-blacks-777/) have sported aircrafts honoring its countries sports teams and culture. Iceland Air even allows people to request its signature [Northern Lights airplane](https://www.icelandair.com/about/our-fleet/hekla-aurora/) to land at an airport near them. Southwest Airlines will occasionally celebrate different states in which it has significant service milestones by rolling out [liveries resembling that state's flag](https://www.bizjournals.com/losangeles/news/2019/02/21/southwest-airlines-uniquely-painted-planes.html).

What are your thoughts? What designs would you like to see most in the sky? Let me know by connecting on [LinkedIn](https://www.linkedin.com/in/jay-cromwell-45329973/)!





